### ISSUE TITLE
USER STORY: Newsletter Form SignUp

### ISSUE THREAD

**Issue by ruimarnjr** [ruimarnjr/ConsoleChase#16]
**As a site user**, I can **provide my information through the newsletter form** to **receive emails regarding products**

**Acceptance Criteria**
- The newsletter signup option is easily accessible in the footer. Users can submit their email to receive information newsletters directly to their inbox.

**Tasks**
- [x] Develop an input form for newsletter subscription.
- [x] Apply styling to enhance the visual appeal of the input form.
- [x] Conduct testing to ensure the successful submission of the form and the reception of email notifications.
