### ISSUE TITLE
USER STORY: Save to Wishlist

### ISSUE THREAD

**Issue by ruimarnjr** [ruimarnjr/ConsoleChase#28]
**As a signed-in user**, I can **click the 'Add to Wishlist' button** to **bookmark favorite items**.

**Acceptance Criteria**
A logged-in user exclusively sees the 'Wishlist' button.
Clicking the 'Wishlist' button adds the selected item to the user's wishlist.
The user can access their wishlist through an icon in the header; however, unauthenticated users will be redirected to the sign-in page.

**Tasks**
- [x] Develop a Wishlist button to facilitate users in saving their favorite items.
- [x] Establish an 'Add to Wishlist' view to manage the addition of items to the user's wishlist.
- [x] Connect the Wishlist icon located in the header to the user's wishlist and redirect unauthenticated users to the sign-in page for access.
